### ISSUE TITLE
Get current scm provider and list of changed resources

### ISSUE THREAD

**Issue by dtretyakov** [Microsoft/vscode-SCMBuilders#3]
In the [preview api](https://github.com/Microsoft/vscode-SCMBuilders/blob/master/api-overview.md) it was possible to get a current scm provider, but it seems that in the final implementation no way to receive a [current scm provider](https://raw.githubusercontent.com/Microsoft/vscode/master/src/vs/vscode.d.ts) and get a list of modified resources.

Is it possible to expose `scmProvider` again?

**Comment by joaomoreno** [comment]
Microsoft/vscode#25838
