### ISSUE TITLE
SCM not avaialbe when published

### ISSUE THREAD

**Issue by JohnstonCode** [Microsoft/vscode-SCMBuilders#4]
HI Team,

I have forked [vscode-svn](https://github.com/INesterov/vscode-svn) to use the SCM API.
[My Version](https://github.com/JohnstonCode/svn-scm)

I have got it working in debug mode on my machine. But when published it is not listed as a SCM provider.

Any help would be appreciated!

**Comment by egamma** [comment]
@JohnstonCode great to see progress on an a SVN SCM provider!

To list the extension as an SCM provider on the marketplace add the "SCM Providers" category in the package.json. Currently you only list `Other` 

```json
  "categories": [
    "SCM Providers",
    "Other"
  ],
```

Here is the mercurial example:
https://github.com/mrcrowl/vscode-hg/blob/master/package.json#L32

**Comment by JohnstonCode** [comment]
@egamma Thanks for getting back to me.

I had already updated my package.json while waiting for a response. This still did not get code to offer it as a SCM provider.

Iv looked at both the mercurial and git SCM source and can't find where I have gone wrong.

Any other suggestions?

**Comment by egamma** [comment]
Actually it now shows up in the category SCM Providers:

![image](https://user-images.githubusercontent.com/172399/30747037-34b166b0-9fac-11e7-9211-061ecd840998.png)

**Comment by JohnstonCode** [comment]
It shows in the marketplace as an SCM Provider.

The issue is still the same inside of code. It only lists git as a SCM.

**Comment by egamma** [comment]
Can you show me a screen shot?

When I try to install additional SCM Providers then I see your extension

![image](https://user-images.githubusercontent.com/172399/30748427-93cd1672-9fb0-11e7-9b53-b4db78bf80ce.png)

**Comment by egamma** [comment]
FYI @joaomoreno

**Comment by JohnstonCode** [comment]
![image](https://user-images.githubusercontent.com/10222719/30748651-db896b6c-9fa8-11e7-8d61-eb9ef76985b8.png)

No option for SVN with the extension installed

**Comment by JohnstonCode** [comment]
Works as expected in debug mode on the extension development host

**Comment by egamma** [comment]
Works for me in the latest stable and insiders, please see the attached recording. What am I missing?

![scm-providers](https://user-images.githubusercontent.com/172399/30749820-cf269442-9fb4-11e7-8b04-96c660f5b8af.gif)

**Comment by JohnstonCode** [comment]
![image](https://user-images.githubusercontent.com/10222719/30750094-65e83d7a-9fad-11e7-8c34-976f8beb6ce0.png)

SVN does not show in the source control pane when installed. I can install mercurial and it shows as in the screenshot above. When I run the extension in debug mode it shows in the Source control pane.

![image](https://user-images.githubusercontent.com/10222719/30750261-e118859a-9fad-11e7-9a76-ecf8f2102b1c.png)

**Comment by egamma** [comment]
I get this error
![image](https://user-images.githubusercontent.com/172399/30752027-5e6a8298-9fbb-11e7-8203-79e86cbe5898.png)

I suspect that the svn-spawn module is not packaged with the extension.

**Comment by egamma** [comment]
yes I can confirm that this module is missing from the packaged extension

**Comment by JohnstonCode** [comment]
![image](https://user-images.githubusercontent.com/10222719/30752300-cddd1486-9fb3-11e7-864a-60cdc85a953b.png)

Thanks for your help. Can't believe I missed that!
