### ISSUE TITLE
SCM Quick diff

### ISSUE THREAD

**Issue by JohnstonCode** [Microsoft/vscode-SCMBuilders#5]
Hi Team, 

Trying to get Quick Diff guttering to show. Looking at the API docs and the GIT and Mercurial implementations They both seem to implement provideOriginalResource and set quickDiffProvider = this.

I have tried to do it here [here](https://github.com/JohnstonCode/svn-scm/blob/0d08627237b61ef1c5d1b2dc638c88ea305d82b5/extension.js#L89) but it doesn't seem to work. Getting IPC watcher errors.

Other attempt looked like [this](https://github.com/JohnstonCode/svn-scm/blob/9d0ee518e39a38e4bd9b9e4ce81892957d41ed2d/extension.js#L106)

**Comment by joaomoreno** [comment]
What errors are you getting? 

Don't forget to [register a content provider](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5137) too, which should return the contents for that resource.

**Comment by JohnstonCode** [comment]
Thank you!
